# Denies TNTs everywhere from destroying non-base blocks
disable-tnt-destroying-non-base-blocks: true

# Denies every base center damage
disable-base-center-damage: false

# Disables the hologram healthbar of the base center
disable-base-center-hologram: false

# How much time the hologram is shown after Base Center takes damage
hologram-seconds-shown-after-damage: 8

# Item which will be used to repair base blocks. Wrench ID is 9377.
# You can put -1 to disable it.
repair-item-id: 9377

# How much health will restore per scrap metal
repair-health-amount: 0.2